emission_rates = {
    'Train': '22',
    'Bus': '22',
    'Plane': '158',
    'Car - Plug In Hybrid': '51',
    'Car - Battery Electric': '0',
    'Car - Typical Petrol': '164',
    'Car - Typical Diesel': '176',
    'Car - Micro': '116',
    'Car - Light': '132',
    'Car - Medium': '137',
    'Car - Large': '198',
    'Car - People Mover': '212',
    'Car - Small/Medium SUV': '156',
    'Car - Large SUV': '195',
    'Motorbike': '110',
    'Electricity (VIC)': '1600',
    'Natural Gas': '69',
    'Other': '1',
    'Offset': '-1'
}